version: "3.8"
services:
  web:
    container_name: "web-app"
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=jdbc:postgresql://ktor-db:5432/postgres
      - POSTGRES_POOL=5
    depends_on:
      db:
        condition: service_healthy
    networks:
      - some-name
  db:
    container_name: "ktor-db"
    image: postgres:15.2
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - some-name

volumes:
  postgres-data:
    driver: local

networks:
  some-name:
    driver: bridge